TASK-4337 Dev: Implement Java code evaluator behind feature flag JAVA_EVAL
For showcasing the ability to invoke arbitrary JuicyRaspberryPie commands (via mc.conn.sendReceive()) and maybe rapid development of new functionality.

,----[ mcpi ]----
| In [2]: mc.conn.sendReceive(b"eval", "System.currentTimeMillis();")
| Out[2]: 'Successful addition of System.currentTimeMillis();: 1720175880010'
`----

Note: The server needs to run with a full JDK; the JRE won't do. The registration uses Java reflection to handle this gracefully. Also, due to the security implications this is behind a feature flag that should only be enabled in development environments.
The JShell code is based on the REPL at https://docs.oracle.com/javase/9/docs/api/jdk/jshell/package-summary.html

Standard JShell instantiation fails with
> java.lang.IllegalStateException: Launching JShell execution engine threw: No ExecutionControlProvider with name 'failover' and parameter keys: [0, 1, 2]
https://forums.minecraftforge.net/topic/112875-java-serviceloader-environment-not-finding-services-when-running-in-forge/ suggests that this is due to the Paper server, and advises to install a LocalExecutionControlProvider.